# Generated by Django 4.2.1 on 2023-09-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=20, unique=True)),
                ('size', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=20, unique=True)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.container')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='containers',
            field=models.ManyToManyField(through='employee_information.ShipmentContainer', to='employee_information.container'),
        ),
        migrations.CreateModel(
            name='MaintenancePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_maintenance_date', models.DateField()),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.shipment')),
            ],
        ),
    ]
