# Generated by Django 4.2.1 on 2023-09-15 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0009_remove_vehicle_maintenance_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle_category',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
