# Generated by Django 4.2.1 on 2023-09-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0013_expense_category_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
