# Generated by Django 4.2.1 on 2023-09-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0014_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='veh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vehicle'),
        ),
    ]
