# Generated by Django 4.2.1 on 2023-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0015_alter_expense_veh_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
