# Generated by Django 4.2.1 on 2023-10-17 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0017_agent_carrier_commodity_contract_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('con', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('con', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('status', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='company_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='stamp',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
