# Generated by Django 4.2.1 on 2023-12-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0018_customer_vendor_agent_email_booking_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='stamp',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_information.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='stamp',
            field=models.ImageField(default=0, upload_to='customer_images/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='con',
            field=models.DecimalField(decimal_places=2, max_digits=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='con',
            field=models.DecimalField(decimal_places=2, max_digits=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='con',
            field=models.DecimalField(decimal_places=2, max_digits=12, unique=True),
        ),
    ]
