# Generated by Django 4.2.1 on 2023-12-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0019_remove_booking_company_name_remove_booking_stamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='con',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
