# Generated by Django 4.2.1 on 2023-12-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0020_alter_customer_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='con',
            field=models.IntegerField(default=0),
        ),
    ]
