# Generated by Django 4.2.1 on 2023-12-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0021_alter_customer_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='con',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='con',
            field=models.IntegerField(default=0),
        ),
    ]
