# Generated by Django 4.2.1 on 2023-12-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0022_alter_agent_con_alter_vendor_con'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_no',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='booking',
            name='stamp',
            field=models.ImageField(default=0, upload_to='booking_images/'),
        ),
    ]
