# Generated by Django 4.2.1 on 2023-12-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0023_booking_order_no_booking_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='com',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
