# Generated by Django 4.2.1 on 2023-12-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0025_rename_shipper_booking_ship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='stamp',
            field=models.ImageField(default=0, upload_to='customer_images/'),
        ),
    ]
