# Generated by Django 4.2.1 on 2023-12-14 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0026_alter_booking_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container_purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('purchase_price', models.IntegerField(default=0)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('Cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vehicle')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Currency_exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500)),
                ('rate', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det', models.CharField(max_length=50)),
                ('Pol', models.CharField(max_length=50)),
                ('Pofd', models.CharField(max_length=50)),
                ('Pol2', models.CharField(max_length=50)),
                ('Pofd2', models.CharField(max_length=50)),
                ('ship', models.CharField(max_length=500)),
                ('tra_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tan_exp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('Commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.commodity')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.agent')),
                ('customer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_information.customer')),
                ('freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.freight_category')),
            ],
        ),
        migrations.CreateModel(
            name='Slot_dete_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('rate', models.IntegerField(default=0)),
                ('slot_start', models.TimeField(default=django.utils.timezone.now)),
                ('slot_end', models.TimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('rate', models.IntegerField(default=0)),
                ('slot_start', models.TimeField(default=django.utils.timezone.now)),
                ('slot_end', models.TimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.container_purchase')),
                ('set_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(default=0, max_length=500)),
                ('stamp', models.ImageField(default=0, upload_to='customer_images/')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('port', models.CharField(max_length=200)),
                ('payment_center', models.CharField(max_length=200)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('pur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.container_purchase')),
                ('set_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.settlement')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='lease_rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('rent_start', models.DateTimeField(auto_now=True)),
                ('rent_end', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.customer')),
                ('con_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ex_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.currency_exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Container_sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('Sale_price', models.IntegerField(default=0)),
                ('Sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('Cont_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vehicle')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.CharField(default=0, max_length=500)),
                ('stamp', models.ImageField(default=0, upload_to='customer_images/')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('port', models.CharField(max_length=200)),
                ('payment_center', models.CharField(max_length=200)),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trans_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.customer')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.booking')),
                ('set_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.settlement')),
            ],
        ),
    ]
