# Generated by Django 4.2.1 on 2023-12-14 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0028_rename_vendor_container_purchase_vens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container_purchase',
            old_name='Cont_id',
            new_name='Con_id',
        ),
    ]
