# Generated by Django 4.2.1 on 2023-12-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0029_rename_cont_id_container_purchase_con_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='container_purchase',
            name='idd',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
