# Generated by Django 4.2.1 on 2023-12-16 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0030_container_purchase_idd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot_dete_invoice',
            name='sale_id',
        ),
        migrations.AddField(
            model_name='slot_dete_invoice',
            name='pur_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee_information.container_purchase'),
        ),
    ]
