# Generated by Django 4.2.1 on 2023-12-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0031_remove_slot_dete_invoice_sale_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot_dete_invoice',
        ),
    ]
