# Generated by Django 4.2.1 on 2023-12-16 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0032_delete_slot_dete_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1, max_length=20)),
                ('rate', models.IntegerField(default=0)),
                ('slot_start', models.TimeField(default=django.utils.timezone.now)),
                ('slot_end', models.TimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('set_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.settlement')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.vehicle')),
            ],
        ),
    ]
