# Generated by Django 4.2.1 on 2023-12-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0033_container_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container_slot',
            old_name='slot_id',
            new_name='pur_id',
        ),
    ]
