# Generated by Django 4.2.1 on 2023-12-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0034_rename_slot_id_container_slot_pur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container_slot',
            name='pur_id',
        ),
        migrations.AddField(
            model_name='container_slot',
            name='con_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_information.vehicle'),
        ),
        migrations.DeleteModel(
            name='Purchase_slot',
        ),
    ]
