# Generated by Django 4.2.1 on 2023-12-17 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0036_special_rate_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_invoice',
            name='set_type',
        ),
    ]
