# Generated by Django 4.2.1 on 2023-12-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0037_remove_booking_invoice_set_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='tran_id',
        ),
        migrations.AddField(
            model_name='exchange',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
