# Generated by Django 4.2.1 on 2023-12-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0039_rename_type_currency_exchange_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_exchange',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
