# Generated by Django 4.2.1 on 2023-12-17 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0040_alter_currency_exchange_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.TextField()),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.booking')),
            ],
        ),
    ]
