# Generated by Django 4.2.1 on 2023-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0041_bookingupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingupdate',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
