# Generated by Django 4.2.1 on 2023-12-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0042_bookingupdate_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipment',
        ),
        migrations.RemoveField(
            model_name='maintenanceprediction',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='containers',
        ),
        migrations.RemoveField(
            model_name='shipmentcontainer',
            name='container',
        ),
        migrations.RemoveField(
            model_name='shipmentcontainer',
            name='shipment',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=1, max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='pay',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='size',
            field=models.CharField(default=1, max_length=20),
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='MaintenancePrediction',
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentContainer',
        ),
    ]
