# Generated by Django 4.2.1 on 2023-12-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0043_delete_inventory_remove_invoice_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
